version: '2'
services:
    projectshare-app:
        image: projectshare
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://projectshare-mysql:3306/projectshare?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    projectshare-mysql:
        extends:
            file: mysql.yml
            service: projectshare-mysql
